# Please do not change this number as it might modify your configuration in unexpected ways.
Version: 1

# Prints helpful messages to the console on certain events to help debugging.
# recommended to keep on false in production environments to avoid spam in your console
DebugMessages: true

# Select your locale from the localization folder
Locale: "en"

Prefix: "&6&lBlockStackerX &7"


# Available Storage Types:
#
# Json Key Features:
#
#   Json is a moderately quick storage method.
#   Its fairly easy to manually change some data in json files
#   Json Requires quite a bit of extra data storage
# Json Type ID: "JSON"
#
#
# Byte Key Features:
#
#   Byte Storage is the fastest available and is about 3.5 Times faster than Json in the best scenario
#   Byte Storage requires the least amount of data on your hard drive
#   Its very difficult to manually change data inside byte files
# Byte Type ID: "BYTE"
#
# Check out these benchmarks for an in depth understanding of each storage method's speeds //TODO Add benchmark link
# If you don't care for readability i highly recommend byte storage
StorageType: "BYTE"

# HD_DISPLAYS (Will attempt to hook into Holographic displays)
# CUSTOM (Will use hologram provided by BlockStackerX)
HologramType: "CUSTOM"

Stacker_Add_Action: "RIGHT_CLICK_BLOCK"
Stacker_Take_Action: "LEFT_CLICK_BLOCK"
