# Please do not change this number as it might modify your configuration in unexpected ways.
Version: 1

# Prints helpful messages to the console on certain events to help debugging.
# recommended to keep on false in production environments to avoid spam in your console
DebugMessages: true

# Select your locale from the localization folder
Locale: "en"

Prefix: "&6&lBlockStackerX &7"